config/urls.py
# config/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

portfolio/urls.py
#  portfolio/urls.py

from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path('', views.hero_page_view, name='hero'),
    path('home', views.about_page_view, name='home'),
    path('about', views.about_page_view, name='about'),
    path('web', views.web_page_view, name='web'),
    path('quizz', views.quizz, name='quizz'),
    path('contactos', views.contactos_page_view, name='contactos'),

    path('blog', views.blog_page_view, name='blog'),
    path('novo/', views.novo_comentario_view, name='novo'),
    path('edita/<int:comentario_id>', views.edita_comentario_view, name='edita'),
    path('apaga/<int:comentario_id>', views.apaga_comentario_view, name='apaga'),
]

portfolio/models.py
from django.db import models

# Create your models here.


class Portfolio(models.Model):
    nome = models.CharField(max_length=100)
    comentario = models.CharField(max_length=600)
    criado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome[:50]


class PontuacaoQuizz(models.Model):
    nome = models.CharField(max_length=64)
    pontuacao = models.IntegerField(max_length=10)


class Linguagem(models.Model):
    nome = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.nome}"



class Professor(models.Model):
    nome = models.CharField(max_length=64)
    numero = models.IntegerField(max_length=10)

    def __str__(self):
        return f"{self.nome}({self.numero})"


class Projeto(models.Model):
    nome = models.CharField(max_length=64)


    def __str__(self):
        return f"{self.nome}({self.id})"


class Cadeira(models.Model):
   nome = models.CharField(max_length=20)
   ano = models.IntegerField()
   descricao = models.TextField()
   linguagens = models.ManyToManyField(Linguagem)
   docente_teorica = models.ForeignKey(Professor, on_delete=models.CASCADE)
   docentes_praticas = models.ManyToManyField(Professor, related_name='caderias')
   projetos = models.ManyToManyField(Projeto)

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from .models import Portfolio


class PortfolioForm(ModelForm):
    class Meta:
        model = Portfolio
        fields = '__all__'
        # inserção de classes CSS para formatação de cada campo do formulário
        widgets = {
            'nome': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Insira o nome a aparecer como autor...'}),
            'comentario': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Escreva aqui o seu comentário...'}),
        }

        # texto a exibir junto à janela de inserção
        labels = {
            'nome': 'Nome',
            'comentario': 'Comentario',
        }

        # texto auxiliar a um determinado campo do formulário
        help_texts = {
            'nome': 'Escreva "Anónimo" caso não queira deixar o seu nome',
        }

portfolio/views.py
#  hello/views.py

import datetime
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Portfolio, PontuacaoQuizz
from .forms import PortfolioForm


def home_page_view(request):
    agora = datetime.datetime.now()
    local = 'Lisboa'
    topicos = ['HTML', 'CSS', 'Python', 'Django', 'JavaScript']

    context = {
        'hora': agora.hour,
        'local': local,
        'topicos': topicos,
    }
    return render(request, 'home.html', context)


def about_page_view(request):
    agora = datetime.datetime.now()
    local = 'Lisboa'
    topicos = ['HTML', 'CSS', 'Python', 'Django', 'JavaScript']

    context = {
        'hora': agora.hour,
        'local': local,
        'topicos': topicos,
    }
    return render(request, 'about.html', context)


def web_page_view(request):
    return render(request, 'web.html')

def contactos_page_view(request):
    return render(request, 'contactos.html')


def projetos_page_view(request):
    return render(request, 'projetos.html')


def hero_page_view(request):
    return render(request, 'hero.html')


def blog_page_view(request):
    context = {'comentarios': Portfolio.objects.all()}
    return render(request, 'blog.html', context)


def novo_comentario_view(request):
    form = PortfolioForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))
    context = {'form': form}
    return render(request, 'novo.html', context)


def edita_comentario_view(request, comentario_id):
    comentario = Portfolio.objects.get(id=comentario_id)
    form = PortfolioForm(request.POST or None, instance=comentario)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {'form': form, 'comentario_id': comentario_id}
    return render(request, 'edita.html', context)


def apaga_comentario_view(request, comentario_id):
    Portfolio.objects.get(id=comentario_id).delete()
    return HttpResponseRedirect(reverse('projeto:blog'))


def pontuacao_quizz(request):
    return request.pontuacao


def quizz(request):
    if request.method == 'POST':
        n = request.POST['nome']
        p = pontuacao_quizz(request)
        r = PontuacaoQuizz(nome=n, pontuacao=p)
        r.save()
    return render(request, 'quizz.html')

portfolio/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Me</title>

  {% load static %}
  <link rel="stylesheet" href="{% static 'portfolio/css/about.css' %}">

    <link rel="icon" type="image/x-icon" href="https://yt3.ggpht.com/ytc/AKedOLTtSIICccWIydxNZ3Cj3QQFukp2OukrFVzoXIdI=s600-c-k-c0x00ffffff-no-rj-rp-mo"/>

</head>

<body>
  <header>
    <p>Tomé Roque</p>
    <nav>
      <a href="{% url 'portfolio:hero' %}">Home</a>
      <a href="{% url 'portfolio:about' %}">About Me</a>
      <a href="{% url 'portfolio:blog' %}">Blog</a>
      <a href="{% url 'portfolio:quizz' %}">Quizz</a>
        <a href="{% url 'portfolio:web' %}">Web</a>
        <a href="{% url 'portfolio:contactos' %}">Contactos</a>
    </nav>
  </header>

  <div id="grad1"><div id="gradup"></div></div>

        <h1>{% if hora > 12 %}
                   Good afternoon,
                {% else %}
                   Good morning,
                {% endif %}
                greetings to {{ local }}, where it is {{ hora }}.<br></h1>


        <h1>This is the page where I talk a little more about myself!</h1>
        <p> <br> As I have established before I am both a programmer and an editor, <br> saying that I have been working on some different projects throught
        my life and this is where I am going to show you some of them aswell as some of my personal experiences<br> </p>

    <div class="exp">
        <div class="uni">University projects</div>
        <div class="noraya">Video editing at Noraya agency</div>
        <div class="fute">Former football player, in the local team</div>
        <div class="care">Monitoring at various summer camps, aswell as multiple people related jobs</div>
        <div class="skills">Personal Skills</div>
    </div>



    <h1> Degree in Computer Science at Universidade Lusófona de Humaninades e Tecnologias</h1>

     <h2><b><a class="universidade" href="https://www.ulusofona.pt" target="_self">Universidade Lusófona de Humanidades e Tecnologias</a></b></h2>

<h2>Cadeiras de Primeiro ano</h2>

<div class="cadeiras1o">
<div>
    <div><img src="{% static 'portfolio/images/fisics.jpg' %}" alt="fisics"></div>
    <div><p>Fundamentals of Physics</p></div>
</div>
<div>
    <div><img src="" alt=""></div>
    <div><p>Digital Systems</p></div>
</div>
    <div>
<div><img src="" alt=""></div>
    <div><p>Discrete Mathematics</p></div>
    </div>
    <div>
<div><img src="{% static 'portfolio/images/math.jpg' %}" alt="math"></div>
    <div><p>Mathematics I</p></div>
    </div>

    <div>
<div><img src="{% static 'portfolio/images/prog.jpg' %}" alt="prog"></div>
    <div><p>Programming Fundamentals</p></div>
    </div>

    <div>
<div><img src="" alt=""></div>
    <div><p>Algorithms and Data Structures</p></div>
    </div>

    <div>
<div><img src="" alt=""></div>
    <div><p>Behavioral Competencies</p></div>
    </div>

    <div>
<div><img src="" alt=""></div>
    <div><p>Computer Architecture</p></div>
    </div>

    <div>
<div><img src="" alt=""></div>
    <div><p>Linear Algebra</p></div>
    </div>

    <div>
<div><img src="{% static 'portfolio/images/math.jpg' %}" alt="math"></div>
    <div><p>Mathematics II</p></div>
    </div>

    <div>
<div><img src="{% static 'portfolio/images/prog.jpg' %}" alt="prog"></div>
    <div><p>Programming Languages I</p></div>
    </div>

</div>


<h2>Cadeiras de Segundo ano</h2>

<div class="cadeiras2o">
<div>
    <div><img src="" alt=""></div>
    <div><p>Advanced Computer Architectures</p></div>
</div>
<div>
    <div><img src="" alt=""></div>
    <div><p>Databases</p></div>
</div>
    <div>
<div><img src="" alt=""></div>
    <div><p>Operating Systems</p></div>
    </div>
    <div>
<div><img src="{% static 'portfolio/images/prog.jpg' %}" alt="prog"></div>
    <div><p>Programming Languages II</p></div>
    </div>

    <div>
<div><img src="" alt=""></div>
    <div><p>Signals and Systems</p></div>
    </div>

    <div>
<div><img src="" alt=""></div>
    <div><p>Computer Networks</p></div>
    </div>

    <div>
<div><img src="" alt=""></div>
    <div><p>Decision Support Systems</p></div>
    </div>

    <div>
<div><img src="" alt=""></div>
    <div><p>Computer Networks</p></div>
    </div>

    <div>
<div><img src="" alt=""></div>
    <div><p>Decision Support Systems</p></div>
    </div>

    <div>
<div><img src="" alt=""></div>
    <div><p>Graphic Computing</p></div>
    </div>

    <div>
<div><img src="" alt=""></div>
    <div><p>Requirements and Test Engeneering</p></div>
    </div>

    <div>
<div><img src="{% static 'portfolio/images/prog.jpg' %}" alt="prog"></div>
    <div><p>Web Programming</p></div>
    </div>
</div>



<h2>Cadeiras de Terceiro ano</h2>

<div class="cadeiras3o">
<div>
    <div><img src="" alt=""></div>
    <div><p>Final Course Work</p></div>
</div>
<div>
    <div><img src="" alt=""></div>
    <div><p>Data Science</p></div>
</div>
    <div>
<div><img src="" alt=""></div>
    <div><p>Distributed Computing</p></div>
    </div>
    <div>
<div><img src="" alt=""></div>
    <div><p>Human-Machine Interaction</p></div>
    </div>

    <div>
<div><img src="" alt=""></div>
    <div><p>Software Engeneering</p></div>
    </div>

    <div>
<div><img src="" alt=""></div>
    <div><p>Artificial Intelligence</p></div>
    </div>

    <div>
<div><img src="" alt=""></div>
    <div><p>Cloud Information Systems</p></div>
    </div>

    <div>
<div><img src="" alt=""></div>
    <div><p>Computer Security</p></div>
    </div>

    <div>
<div><img src="" alt=""></div>
    <div><p>Mobile Computing</p></div>
    </div>


</div>


</body>
</html>

portfolio/templates/blog.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block main %}
    {% for comentario in portfolio %}
        <p> 
           {{ comentario.nome }}
           <a href="{% url 'portfolio:edita' comentario.id %}" class="btn btn-warning">Editar comentário</a>
        </p>
   {% endfor %}
        <a href="{% url 'portfolio:novo' %}" class="btn btn-success btn-block">Novo comentário</a>
{% endblock %}

portfolio/templates/contactos.html
{% extends 'portfolio/layout.html' %}

{% load static %}

{% block title %}Web{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'portfolio/css/contactos.css' %}">



{% endblock %}


{% block main %}

<h1>Contactos</h1>

<p><a href="https://www.linkedin.com/in/tom%C3%A9-roque-774752182">LinkedIn</a> <br>
<br><a href="https://github.com/TomeRoque-21807126">github</a> <br>
<br>a21807126@alunos.ulht.pt<br><br> from Torres Vedras</p>


{% endblock %}

portfolio/templates/edita.html
{% extends 'tarefas/base.html' %}

{% load static %}

{% block main %}
<h3>Comentário</h3>
    <form action="{% url 'portfolio:edita' comentario_id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'portfolio:blog' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
        <a href="{% url 'portfolio:apaga' comentario_id %}" role="button" class="btn btn-danger">Apagar</a>
    </form>

{% endblock %}

portfolio/templates/hero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bem vindo!</title>

  {% load static %}
  <link rel="stylesheet" href="{% static 'portfolio/css/hero.css' %}">

  <link rel="icon" type="image/x-icon" href="https://yt3.ggpht.com/ytc/AKedOLTtSIICccWIydxNZ3Cj3QQFukp2OukrFVzoXIdI=s600-c-k-c0x00ffffff-no-rj-rp-mo"/>

</head>

<body>
  <header>
    <p>Tomé Roque</p>
    <nav>
      <a href="{% url 'portfolio:hero' %}">Home</a>
      <a href="{% url 'portfolio:about' %}">About Me</a>
      <a href="{% url 'portfolio:blog' %}">Blog</a>
      <a href="{% url 'portfolio:quizz' %}">Quizz</a>
      <a href="{% url 'portfolio:web' %}">Web</a>
      <a href="{% url 'portfolio:contactos' %}">Contactos</a>

    </nav>
  </header>

  <main>
    <p>Welcome to my Digital Portfolio!</p>
  </main>

  <article class="primeiro">
    <p><b><i>Meet Tomé Roque.</i></b> Programmer & Editor <br><br>
    Hey there! As you already know, my name is Tomé Roque. A small town boy who grew up to take a degree in computer science
      while also having a passion for photo and video editing, having been involved in projects on both matters. <br>
      Living in a world where people should enjoy what they do, I also make some of my own work mainly for fun purposes.
      Have a look around my website and discover them for yourselves!
    </p>
  </article>

  <article class='segundo'>
  </article>

  <footer>
    <p>Tomé Roque ♠ Website desenvolvido em 2022</p>

  </footer>
</body>

</html>

portfolio/templates/home.html
{% extends 'portfolio/layout.html' %}

{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/css/base.css' %}">


<link rel="stylesheet" href="../static/portfolio/css/base.css">

{% block main %}
	<h3>Bem Vindo!</h3>
    <p>Eu sou o Tomé Roque, e este é o meu portfolio!</p>

    {% load static %}
    <img src="{% static 'portfolio/images/image.png' %}">
{% endblock %}

portfolio/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bem vindo!</title>

  {% load static %}
  <link rel="stylesheet" href="{% static 'portfolio/css/hero.css' %}">

  <link rel="icon" type="image/x-icon" href="https://yt3.ggpht.com/ytc/AKedOLTtSIICccWIydxNZ3Cj3QQFukp2OukrFVzoXIdI=s600-c-k-c0x00ffffff-no-rj-rp-mo"/>

</head>

<body>
  <header>
    <p>Tomé Roque</p>
    <nav>
      <a href="{% url 'portfolio:hero' %}">Home</a>
      <a href="{% url 'portfolio:about' %}">About Me</a>
      <a href="{% url 'portfolio:blog' %}">Blog</a>
      <a href="{% url 'portfolio:quizz' %}">Quizz</a>
      <a href="{% url 'portfolio:web' %}">Web</a>
      <a href="{% url 'portfolio:contactos' %}">Contactos</a>

    </nav>
  </header>

  <main>
    <p>Welcome to my Digital Portfolio!</p>
  </main>

  <article class="primeiro">
    <p><b><i>Meet Tomé Roque.</i></b> Programmer & Editor <br><br>
    Hey there! As you already know, my name is Tomé Roque. A small town boy who grew up to take a degree in computer science
      while also having a passion for photo and video editing, having been involved in projects on both matters. <br>
      Living in a world where people should enjoy what they do, I also make some of my own work mainly for fun purposes.
      Have a look around my website and discover them for yourselves!
    </p>
  </article>

  <article class='segundo'>
  </article>

  <footer>
    <p>Tomé Roque ♠ Website desenvolvido em 2022</p>

  </footer>
</body>

</html>

portfolio/templates/novo.html
{% extends 'portfolio/base.html' %}

{% load static %}

{% block main %}
<h3>Novo Comentário</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'portfolio:blog' %}" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>
{% endblock %}

portfolio/templates/portfolio/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Comentários</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎯</text></svg>">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/blog.css' %}">
</head>
<body>
<header class="menu">
    <p class="nomeMenu">Tomé Roque</p>
    <nav class="hrefMenu">
      <a href="{% url 'portfolio:hero' %}">Home</a>
      <a href="{% url 'portfolio:about' %}">About Me</a>
      <a href="{% url 'portfolio:blog' %}">Blog</a>
      <a href="{% url 'portfolio:quizz' %}">Quizz</a>
        <a href="{% url 'portfolio:web' %}">Web</a>
        <a href="{% url 'portfolio:contactos' %}">Contactos</a>
    </nav>
  </header>

    <header class="jumbotron text-center">
        <h1>Comments</h1>
        <hr width="30%">
        <p>Leave a comment, tips are always welcome!</p>
    </header>

    <main class="container text-center">
    {% block main %}

    {% endblock %}
    </main>
    <footer>Portfólio Tomé Roque - ULHT</footer>
</body>
</html>

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}{% endblock %}</title>




    <link rel="icon" type="image/x-icon" href="https://yt3.ggpht.com/ytc/AKedOLTtSIICccWIydxNZ3Cj3QQFukp2OukrFVzoXIdI=s600-c-k-c0x00ffffff-no-rj-rp-mo"/>


    <link rel="stylesheet" href="{% static 'portfolio/css/layout.css' %}">
    {% block styles %}

    {% endblock %}


</head>
<body>
  <header>
    <div>Tomé Roque</div>
    <nav>
      <a href="{% url 'portfolio:hero' %}">Home</a>
      <a href="{% url 'portfolio:about' %}">About Me</a>
      <a href="{% url 'portfolio:blog' %}">Blog</a>
        <a href="{% url 'portfolio:quizz' %}">Quizz</a>
      <a href="{% url 'portfolio:web' %}">Web</a>
        <a href="{% url 'portfolio:contactos' %}">Contactos</a>

    </nav>
  </header>

  <main>
	{% block main %}
	{% endblock main %}
  </main>

  <body>
  {% block body %}

  {% endblock body %}
  </body>
  <footer>
      <div><p>Tomé Roque ♠ Website desenvolvido em 2022</p></div>
  </footer>
</body>
</html>

portfolio/templates/projetos.html
{% extends 'portfolio/layout.html' %}

{% block main %}



{% endblock %}

portfolio/templates/quizz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bem vindo!</title>

  {% load static %}
  <link rel="stylesheet" href="{% static 'portfolio/css/quizz.css' %}">

    <link rel="stylesheet" href="../static/portfolio/css/quizz.css">

</head>

<body>
  <header>
    <p>Tomé Roque</p>
    <nav>
      <a href="{% url 'portfolio:hero' %}">Home</a>
      <a href="{% url 'portfolio:about' %}">About Me</a>
      <a href="{% url 'portfolio:blog' %}">Blog</a>
      <a href="{% url 'portfolio:quizz' %}">Quizz</a>
        <a href="{% url 'portfolio:web' %}">Web</a>
        <a href="{% url 'portfolio:contactos' %}">Contactos</a>
    </nav>
  </header>


<section>
        <h3>Quizz</h3>
        <p>In this page you will be tested about you knollege on html</p>

        <form method="POST">
            <fieldset>
                On HTML
            <fieldset>
                <title>info</title>
                <input type="text" name="nome" placeholder="insira o seu nome">
                <br>
            </fieldset>
            </fieldset>

            <fieldset>
                <title>Questions</title>
                <label><b>Question 1:</b> HTML stands for...</label>
                <br>
                <input type="radio" id="pais1" name="pais" value="portugal"><label for="pais1"> High Tension Multimedia LANs</label><br>
                <input type="radio" id="pais2" name="pais" value="espanha"><label for="pais2"> HyperText Markup Language</label><br>
                <input type="radio" id="pais3" name="pais" value="brasil"><label for="pais3"> HardText Makeup Language</label>
                <br>
                <br>
                <label><b>Question 2:</b> HTML is a language used mainly for <input type="text" id="emisferio" name="emisferio" placeholder="games / websites / data bases / cicles"><label for="emisferio"></label></label>
                <br>
                <br>
                <label><b>Question 3:</b> Django has support for:</label><br>
                <input type="checkbox" id="known1" name="known1" value="praia"><label for="known1">inherit</label><br>
                <input type="checkbox" id="known2" name="known2" value="chuva"><label for="known2">Cicles</label><br>
                <input type="checkbox" id="known3" name="known3" value="mare"><label for="known3">Load static files</label><br>
                <input type="checkbox" id="known4" name="known4" value="turismo"><label for="known4">couple of drinks</label><br>
                <input type="checkbox" id="known5" name="known5" value="calor"><label for="known5">I dont even know anymore</label><br>
                <br>
                <br>
                <textarea id="comentario" name="comentario" rows="4" cols="50" placeholder="Escreva um Comentário"></textarea>
                <br>
                <br>

                <input type="submit">
            </fieldset>
        </form>
    </section>






<footer>
    <p>Tomé Roque ♠ Website desenvolvido em 2022</p>

  </footer>

</body>
</html>

portfolio/templates/web.html
{% extends 'portfolio/layout.html' %}

{% load static %}

{% block title %}Web{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'portfolio/css/web.css' %}">



{% endblock %}


{% block main %}

<div id="grad1"><div id="gradup"></div></div>

<h1>Sobre este Website<br></h1>

<div id="diagrama">

    <img src="{% static 'portfolio/images/diagrama.png' %}">

</div>

<h1> Estrutura do site </h1>

<iframe width="560" height="315" src="https://www.youtube.com/embed/g1DsE_qHw9s" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



<p>Em ciência da computação, front-end, interface frontal ou parte frontal e back-end, parte secundária, parte de suporte ou parte de retaguarda são termos generalizados que se referem às etapas inicial e final de um processo. O front-end é responsável por coligir a entrada do usuário em várias formas e processá-la para adequá-la a uma especificação em que o back-end a possa utilizar.
    <br></p>
<h2>Algumas tecnologias para web front-end e back-end</h2>
<h3>Front-end</h3>
<p>React<br>
XHTML<br>
HTML5<br>
CSS<br>
Javascript<br>
AJAX<br>
jQuery<br>
CFML<br>
AngularJS<br>
Angular<br>
    Vue<br></p>
<h2>Back-end</h2>
<p>PHP<br>
C<br>
C++<br>
Node.js<br>
Ruby on Rails<br>
Python<br>
Java<br>
JSP<br>
.NET<br>
C♯<br>
VB<br>
Perl Catalyst<br></p>
<p style="colour: grey">Texto retirado do wikipedia</p>
{% endblock %}